catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('pet_list/', views.PetListView.as_view(), name='pet_list'),
    path('pet_detail/<int:pk>', views.PetDetail.as_view(), name='pet_detail'),
    path('pet/create/', views.PetCreate.as_view(), name='pet_create'),
    path('pet/<int:pk>/update/', views.PetUpdate.as_view(), name='pet_update'),
    path('pet/<int:pk>/delete/', views.pet_delete, name='pet_delete'),
    path('pet_images/', views.pet_image_list, name='pet_image_list'),
    path('pet/<int:pk>/like/', views.LikePet.as_view(), name='like_pet'),
    path('pet/<int:pk>/dislike/', views.DislikePet.as_view(), name='dislike_pet'),

]

fluffnscales/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


register/urls.py
from django.urls import path
from . import views
urlpatterns = [
 path('register/', views.register, name='register'),
]

catalog/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
import uuid  # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date


class Pet(models.Model):
    """Model representing an animal."""
    pet_name = models.CharField(max_length=100)
    pet_image = models.ImageField(upload_to='images/', null=True, blank=True)
    uploaded_user = models.CharField(max_length=120, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='liked_pets', blank=True)
    dislikes = models.ManyToManyField(User, related_name='disliked_pets', blank=True)

    class Meta:
        ordering = ['pet_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular animal instance."""
        return reverse('pet_detail', args=[str(self)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.pet_name}'

register/models.py
from django.db import models

# Create your models here.

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

catalog/views.py
from .models import Pet
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.views.generic import RedirectView
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


def index(request):
    return render(request, 'catalog/index.html')


class PetDetail(DetailView):
    model = Pet
    template_name = 'catalog/pet_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        total_likes = obj.get_total_likes()
        total_dislikes = obj.get_total_dislikes()
        context['total_likes'] = total_likes
        context['total_dislikes'] = total_dislikes
        context['liked'] = False
        context['disliked'] = False
        if self.request.user.is_authenticated:
            if obj.likes.filter(id=self.request.user.id).exists():
                context['liked'] = True
            if obj.dislikes.filter(id=self.request.user.id).exists():
                context['disliked'] = True
        return context


@method_decorator(login_required, name='dispatch')
class LikePet(LoginRequiredMixin, CreateView):
    model = Pet
    fields = []
    template_name = 'catalog/pet_like.html'

    def post(self, request, pk, *args, **kwargs):
        pet = get_object_or_404(Pet, pk=pk)
        if pet.likes.filter(id=request.user.id).exists():
            pet.likes.remove(request.user)
        else:
            pet.likes.add(request.user)
            pet.dislikes.remove(request.user)
        return redirect('pet_image_list')


@method_decorator(login_required, name='dispatch')
class DislikePet(LoginRequiredMixin, CreateView):
    model = Pet
    fields = []
    template_name = 'catalog/pet_dislike.html'

    def post(self, request, pk, *args, **kwargs):
        pet = get_object_or_404(Pet, pk=pk)
        if pet.dislikes.filter(id=request.user.id).exists():
            pet.dislikes.remove(request.user)
        else:
            pet.dislikes.add(request.user)
            pet.likes.remove(request.user)
        return redirect('pet_image_list')


class PetCreate(LoginRequiredMixin, CreateView):
    model = Pet
    fields = ['pet_name', 'pet_image', 'description']
    success_url = reverse_lazy('pet_image_list')

    def form_valid(self, form):
        # Set the uploaded_user field to the first name of the logged-in user
        form.instance.uploaded_user = self.request.user.username
        return super().form_valid(form)


class PetUpdate(UpdateView):
    model = Pet
    fields = ['pet_name', 'pet_image']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        return HttpResponseRedirect(reverse('pet_list'))


def pet_delete(request, pk):
    pet = get_object_or_404(Pet, pk=pk)
    pet.delete()
    messages.success(request, (pet.pet_name + " has been deleted"))
    return redirect('pet_list')


def pet_image_list(request):
    pets = Pet.objects.exclude(pet_image='').order_by('pet_name')
    return render(request, 'catalog/pet_image_list.html', {'pets': pets})


class PetListView(LoginRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'catalog/pet_list.html'
    login_url = 'login'

    def get_queryset(self):
        return Pet.objects.filter(user=self.request.user)



register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth.models import User, Group


# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data['username']
            form.save()
            # get the new user info and set the group for this user to LibraryMember
            user = User.objects.get(username=uname)
            lib_group = Group.objects.get(name='LibraryMember')
            user.groups.add(lib_group)
            user.save()
            return redirect('login')
        return redirect("index")
    else:
        form = RegisterForm()

    return render(request, "catalog/register.html", {"form": form})

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<link rel="icon" href="static/Rectangle 41 (2).png" type="image/x-icon" />

 <title>{% block title %}Fluff n Scales{% endblock %}</title>
</head>
<body>
<nav>
  <ul class="left-menu">
    <li {% if request.resolver_match.view_name == 'index' %}class="active"{% endif %}>
      <a href="{% url 'index' %}"><i class="fas fa-paw"></i> Fluff N' Scales</a>
    </li>

     <li {% if request.resolver_match.view_name == 'pet_create' %}class="active"{% endif %}>
        <a class="nav-link" href="{% url 'pet_create' %}"><i class="fas fa-plus-circle"></i> New Post</a>
      </li>
      <li {% if request.resolver_match.view_name == 'pet_image_list' %}class="active"{% endif %}>
        <a class="nav-link" href="{% url 'pet_image_list' %}"><i class="fas fa-images"></i> Feed</a>
      </li>
      </ul>
  <ul class="right-menu">
    {% if user.is_authenticated %}

      <li {% if request.resolver_match.view_name == 'logout' %}class="active"{% endif %}>
        <a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> {{ user.username }} Logout</a>
      </li>
    {% else %}
      <li {% if request.resolver_match.view_name == 'login' %}class="active"{% endif %}>
        <a href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Login</a>
      </li>
      <li {% if request.resolver_match.view_name == 'register' %}class="active"{% endif %}>
        <a href="{% url 'register' %}"><i class="fas fa-user-plus"></i> Sign Up</a>
      </li>
    {% endif %}
  </ul>
</nav>


<div class="container1" >
 <br/>
 {% block content %}
 {% endblock %}
</div>

</body>
<style>
body{
margin:0;
 font-family: Arial, Helvetica, sans-serif;
}
nav {
  display: flex;
  justify-content: space-between;
  background-color:blue;

}

nav ul.left-menu {
  margin: 0;
  padding: 0;
  list-style: none;
}

nav ul.right-menu {
  margin: 0;
  padding: 0;
  list-style: none;
  display: flex;
  align-items: center;
}

nav li {
  margin: 0 10px;
  float: left;

}

nav li.active {
  background-color: darkblue;
}

nav li a {
  display: block;
  color:white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

nav li a:hover {
  background-color:#357ae8;
}

.fa {
  margin-right: 5px;
}

.container1 {


}

</style>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}
    <style>
   *{
  text-align: center;

}

body{
  font-family: Arial, Helvetica, sans-serif;
}

h1{
  color: orange;
  margin-bottom: 8px;
  font-size: 60px;
}
h2{
  font-size: 35px;
  color: blue;
  padding: 2px;
}
p{
  font-size: 25px;
  margin-bottom: 2px;
}
.dog1{
  height: 350px;
  width: auto;
  padding-left: 100px;
  padding-right: 100px;
}
.dog2{
  height: 350px;
  width: auto;
  padding-left: 100px;
  padding-right: 100px;
  padding-top: 0;
}

    </style>
<div class="welcome" style="text-align: left;font-size: 25px;">
    {% if user.is_authenticated %}
        Welcome, {{ user.first_name }} {{ user.last_name }}
    {% endif %}
</div>
<h1>Fluff N' Scales</h1>
<h2>We Love Animals!</h2>
{% load static %}
<img class ="dog1" src="{% static 'dog1.jpg' %}">

<img class ="dog2" src="{% static 'dog2.jpg' %}">
<br>

{% endblock %}

catalog/templates/catalog/pet_delete.html
{% extends "catalog/base.html" %}
{% block content %}

{% endblock %}

catalog/templates/catalog/pet_detail.html
{% extends "catalog/base.html" %}
{% block content %}

{% endblock %}

catalog/templates/catalog/pet_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block title %}Add Pet{% endblock %}

{% block content %}
  <style>
    /* Set a max-width for the form */
    form {
      max-width: 500px;
      width: 303px;
      margin: 0 auto;
    }

    /* Add padding to form elements */
    .form-group {
      padding: 10px;
    }

    /* Style the submit button */
    input[type="submit"] {
    background-color: #4d90fe;
    border: none;
    border-radius: 5px;
    color: #fff;
    cursor: pointer;
    font-size: 16px;
    font-weight: bold;
    margin-top: 10px;
    padding: 10px;
    width: 105%;
  }
  input[type="submit"]:hover {
    background-color: #357ae8;
  }

    /* Style the file input */
    input[type="file"] {
      border: none;
      padding: 5px;
      background-color: #f5f5f5;
    }

    /* Style the form labels */
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }

    /* Style form input fields */
    input[type="text"], input[type="password"], select {
      width: 99%;
      padding: 10px;
      border: none;
      border-bottom: 1px solid #ddd;
      background-color: #f5f5f5;
    }

    /* Style form error messages */
    .errorlist {
      color: red;
    }
  </style>

  {% if perms.catalog.add_pet or perms.catalog.edit_pet %}
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Upload">
    </form>
  {% else %}
    You do not have permission to access this feature. <a href="{% url 'index' %}">Home</a>
  {% endif %}
{% endblock %}

catalog/templates/catalog/pet_image_list.html
{% extends "catalog/base.html" %}
{ % load static %}
{% block content %}
<style>

  .animal-name {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .animal-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 100vh;
    text-align: center;
  }

  .animal-card {
    border: 1px solid #ddd;
    border-radius: 5px;
    padding: 10px;
    margin: 10px;
    box-shadow: 0px 0px 5px #ddd;
    max-width: 600px;
  }

  .animal-card img {
    max-width: 100%;
    height: auto;
    margin-top: 10px;
  }

  .animal-posted {
    text-align: left;
    padding-left: 4px;
    padding-bottom: 9px;
  }

  .like-dislike-buttons {
    display: flex;
    justify-content: space-between;
    width: 100%;
    margin-top: 10px;
  }

  .like-button,
  .dislike-button {
    border: none;
    background-color: transparent;
    font-size: 18px;
    cursor: pointer;
    display: flex;
    align-items: center;
    color: #333;
  }

  .like-button i,
  .dislike-button i {
    margin-right: 5px;
  }

  .like-button span,
  .dislike-button span {
    margin-left: 5px;
  }

  /* Media query for small screens */
  @media only screen and (max-width: 767px) {
    .animal-container {
      padding-top: 60px;
    }
    .animal-card {
      max-width: 90%;
    }
  }

  .like-button {
  color: red;

  padding: 6px 12px;
  font-size: 16px;
  cursor: pointer;
}

.like-button.liked {
  background-color: #007bff;
  color: #fff;
  border: none;
}

.like-button.liked:hover {
  background-color: #0069d9;
}

</style>




<div>
  <h2 style="text-align: center;margin-bottom: 5px;">Explore</h2>
{% if pets %}
  <div class="animal-container">
    {% for pet in pets %}
      <div class="animal-card">
        <div class="animal-name">{{ pet.pet_name }}</div>
        <div class="animal-posted">Posted by: {{ pet.uploaded_user }}</div>
        <div class="animal-description">{{ pet.description }}</div>
        <img src="{{ pet.pet_image.url }}" alt="{{ pet.pet_name }}">
        <div class="like-dislike-buttons">
          <form id="like-form" method="POST" action="{% url 'like_pet' pet.pk %}">
            {% csrf_token %}
            <button type="submit" class="like-button  {% if liked_by_user %}liked{% endif %}">
              {% if user in pet.likes.all %}
                <i class="fas fa-heart"></i>
              {% else %}
                <i class="far fa-heart"></i>
              {% endif %}
              <span>{{ pet.likes.count }}</span>
            </button>
          </form>
          <form method="POST" action="{% url 'dislike_pet' pet.pk %}">
            {% csrf_token %}
            <button type="submit" class="dislike-button">
              {% if user in pet.dislikes.all %}
                <i class="fas fa-thumbs-down"></i>
              {% else %}
                <i class="far fa-thumbs-down"></i>
              {% endif %}
              <span>{{ pet.dislikes.count }}</span>
            </button>
          </form>
        </div>
      </div>
    {% endfor %}
  </div>
{% else %}
  <p>There are no pets :(</p>
{% endif %}
</div>



{% endblock %}

catalog/templates/catalog/pet_list.html
{% extends "catalog/base.html" %}

{% block content %}

{% endblock %}

catalog/templates/catalog/register.html

{% extends "catalog/base.html" %}
{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% block content %}


<style>
 /* Center the content */
 body{
  background-color: white;
    font-family: Arial, sans-serif;
    font-size: 18px;
    margin: 0;
 }
.form-group {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-top: 30px;
}

/* Style the heading */
h1 {
  font-size: 24px;
  font-weight: bold;
  text-align: left;
  margin-bottom: 10px;
  padding-left: 20px;
}

/* Style the form */
form {
  width: 50%;
  margin: auto;
 text-align: center;
}

/* Style the form fields */
input[type="text"]{
  width: 250px;
  padding: 10px;
  margin-bottom: 20px;
  border: none;
  border-radius: 5px;
  background-color: #f2f2f2;

}
input[type="email"]{
  width: 250px;
  padding: 10px;
  margin-bottom: 20px;
  border: none;
  border-radius: 5px;
  background-color: #f2f2f2;

}
input[type="password"] {
  width: 250px;
  padding: 10px;
  margin-bottom: 20px;
  border: none;
  border-radius: 5px;
  background-color: #f2f2f2;
}

input[type="text"]:focus,
input[type="email"]:focus,
input[type="password"]:focus {
  outline: none;
  box-shadow: 0px 0px 5px #4d90fe;
}

/* Style the form button */
button[type="submit"] {
  width: 150px;
  padding: 10px;
  border: none;
  border-radius: 5px;
  background-color: #4d90fe;
  color: #fff;
  font-size: 16px;
  cursor: pointer;
}

button[type="submit"]:hover {
  background-color: #357ae8;
}

/* Style the login link */
p {
  margin-top: 20px;
  text-align: center;
}

a {
  color: #4d90fe;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}
ul{
 text-align: left;
}

</style>
 <form method="POST" class="form-group">
 {% csrf_token %}
 {{ form|crispy }}
 <button type="submit" class="btn btn-success">Register</button>
 </form>
 <p><strong>Already have an account?</strong>
 <a href="{% url 'login' %}"> Login Now</a>
 </p>
{% endblock %}
</html>